<a href="https://colab.research.google.com/github/Vivek-Kumar76/AI-powered-travelling-assistant-agentic-AI-/blob/main/Movies_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving tmdb_5000_credits.csv to tmdb_5000_credits.csv

In [ ]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [ ]:
movies.sample(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1327,37000000,"[{""id"": 18, ""name"": ""Drama""}]",http://creedthemovie.com/,312221,"[{""id"": 240, ""name"": ""underdog""}, {""id"": 6075,...",en,Creed,The former World Heavyweight Champion Rocky Ba...,57.773583,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-11-25,173567581,133.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Your legacy is more than a name,Creed,7.3,1915
511,75000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",NaN,36657,"[{""id"": 1852, ""name"": ""mutant""}, {""id"": 8828, ...",en,X-Men,"Two mutants, Rogue and Wolverine, come to a pr...",4.668910,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2000-07-13,296339527,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Evolution Begins,X-Men,6.8,4097

In [ ]:
credits.sample(2)

,movie_id,title,cast,crew
212,435,The Day After Tomorrow,"[{""cast_id"": 19, ""character"": ""Jack Hall"", ""cr...","[{""credit_id"": ""547c22efc3a3685b0000250d"", ""de..."
3926,28005,Kama Sutra - A Tale of Love,"[{""cast_id"": 1, ""character"": ""Maya"", ""credit_i...","[{""credit_id"": ""52fe4572c3a368484e05ba13"", ""de..."

In [ ]:
df=movies.merge(credits,on='title')
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
d_df=df[['movie_id','title','overview','genres','keywords','cast','crew']]
d_df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
d_df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
d_df.dropna(inplace=True)

/tmp/ipython-input-223472184.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df.dropna(inplace=True)

In [ ]:
d_df.duplicated().sum()

np.int64(0)

In [ ]:
def convert(obj):
  l=[]
  for i in eval(obj):
    l.append(i['name'])
  return l

In [ ]:
#d_df['genres']=d_df['genres'].apply(convert)
d_df['keywords']=d_df['keywords'].apply(convert)

/tmp/ipython-input-1388530068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['keywords']=d_df['keywords'].apply(convert)

In [ ]:
def convert3(obj):
  l=[]
  counter=0
  for i in eval(obj):
    if counter!=3:
      l.append(i['name'])
      counter+=1
    else:
      break
  return l

In [ ]:
d_df['cast']=d_df['cast'].apply(convert3)

/tmp/ipython-input-3789409577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['cast']=d_df['cast'].apply(convert3)

In [ ]:
def fetch_director(obj):
  l=[]
  for i in eval(obj):
    if i['job']=='Director':
      l.append(i['name'])
      break
  return l

In [ ]:
d_df['crew']=d_df['crew'].apply(fetch_director)

/tmp/ipython-input-1187619688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['crew']=d_df['crew'].apply(fetch_director)

In [ ]:
d_df['overview']=d_df['overview'].apply(lambda x:x.split())

/tmp/ipython-input-3645883474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['overview']=d_df['overview'].apply(lambda x:x.split())

In [ ]:
d_df['genres']=d_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
d_df['keywords']=d_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
d_df['cast']=d_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
d_df['crew']=d_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

/tmp/ipython-input-1495840101.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['genres']=d_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1495840101.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['keywords']=d_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1495840101.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['cast']=d_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
/tmp/ipython-input-1495840101.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['crew']=d_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
d_df['tags']=d_df['overview']+d_df['genres']+d_df['keywords']+d_df['cast']+d_df['crew']

/tmp/ipython-input-2679982810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_df['tags']=d_df['overview']+d_df['genres']+d_df['keywords']+d_df['cast']+d_df['crew']

In [ ]:
new_df=d_df[['movie_id','title','tags']]

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipython-input-487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [ ]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/tmp/ipython-input-4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [ ]:
new_df['tags']=new_df['tags'].apply(stem)

/tmp/ipython-input-3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [ ]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Spider')

From Paris with Love
The R.M.
Charlie St. Cloud
Killers
Chasing Papi